apiVersion: v1
kind: Namespace
metadata:
  name: clusterpedia-system-0110
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: clusterpedia-internalstorage
  namespace: clusterpedia-system-0110
data:
  internalstorage-config.yaml: |
    type: "postgres"
    host: "clusterpedia-internalstorage-postgres"
    port: 5432
    user: postgres
    database: "clusterpedia"
