run:
  timeout: 10m
  modules-download-mode: vendor
linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - dupl
    - errcheck
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - whitespace
linters-settings:
  goimports:
    local-prefixes: github.com/clusterpedia-io
  misspell:
    ignore-words:
      - creater
output:
  sort-results: true
