apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1beta1.clusterpedia.io-208003
spec:
  insecureSkipTLSVerify: true
  group: clusterpedia.io
  groupPriorityMinimum: 1000
  versionPriority: 100
  service:
    name: clusterpedia-apiserver
    namespace: clusterpedia-system
  version: v1beta1
