apiVersion: v1
kind: ServiceAccount
metadata:
  name: clusterpedia-binding-apiserver
  namespace: clusterpedia-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterpedia
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: clusterpedia
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: clusterpedia
subjects:
- kind: ServiceAccount
  name: clusterpedia-binding-apiserver
  namespace: clusterpedia-system
---
apiVersion: v1
kind: Service
metadata:
  name: clusterpedia-binding-apiserver
  namespace: clusterpedia-system
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: clusterpedia-binding-apiserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: clusterpedia-binding-apiserver
  name: clusterpedia-binding-apiserver
  namespace: clusterpedia-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clusterpedia-binding-apiserver
  template:
    metadata:
      labels:
        app: clusterpedia-binding-apiserver
    spec:
      containers:
      - command:
        - /usr/local/bin/binding-apiserver
        - --secure-port=443
        - --storage-name=memory
        - -v=3
        image: ghcr.io/clusterpedia-io/clusterpedia/binding-apiserver:latest
        name: binding-apiserver
      serviceAccountName: clusterpedia-binding-apiserver
---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1beta1.clusterpedia.io
spec:
  group: clusterpedia.io
  groupPriorityMinimum: 1000
  insecureSkipTLSVerify: true
  service:
    name: clusterpedia-binding-apiserver
    namespace: clusterpedia-system
  version: v1beta1
  versionPriority: 100
