apiVersion: v1
kind: Namespace
metadata:
  name: clusterpedia-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: clusterpedia-system-0110
---
apiVersion: v1
data:
  internalstorage-config.yaml: |
    type: "postgres"
    host: "clusterpedia-internalstorage-postgres"
    port: 5432
    user: postgres
    database: "clusterpedia"
kind: ConfigMap
metadata:
  name: clusterpedia-internalstorage
  namespace: clusterpedia-system-0110
---
apiVersion: v1
data:
  internalstorage-config.yaml: |
    type: "mysql"
    host: "clusterpedia-internalstorage-mysql"
    port: 3306
    user: root
    database: "clusterpedia"
kind: ConfigMap
metadata:
  name: clusterpedia-internalstorage
  namespace: clusterpedia-system
---
apiVersion: v1
data:
  password: ZGFuZ2Vyb3VzMA==
kind: Secret
metadata:
  labels:
    app: clusterpedia-internalstorage
    internalstorage.clusterpedia.io/type: postgres
  name: internalstorage-password
  namespace: clusterpedia-system-0110
---
apiVersion: v1
data:
  password: ZGFuZ2Vyb3VzMA==
kind: Secret
metadata:
  labels:
    app: clusterpedia-internalstorage
    internalstorage.clusterpedia.io/type: mysql
  name: internalstorage-password
  namespace: clusterpedia-system
---
apiVersion: v1
kind: Service
metadata:
  name: clusterpedia-internalstorage-mysql
  namespace: clusterpedia-system
spec:
  ports:
  - port: 3306
  selector:
    app: clusterpedia-internalstorage
    internalstorage.clusterpedia.io/type: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: clusterpedia-internalstorage-postgres
  namespace: clusterpedia-system
spec:
  ports:
  - port: 5432
  selector:
    app: clusterpedia-internalstorage
    internalstorage.clusterpedia.io/type: postgres
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: internalstorage-mysql
  namespace: clusterpedia-system
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  selector:
    matchLabels:
      app: clusterpedia-internalstorage
      internalstorage.clusterpedia.io/type: mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: internalstorage-postgres
  namespace: clusterpedia-system
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  selector:
    matchLabels:
      app: clusterpedia-internalstorage
      internalstorage.clusterpedia.io/type: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: clusterpedia-internalstorage
    internalstorage.clusterpedia.io/type: mysql
  name: clusterpedia-internalstorage-mysql
  namespace: clusterpedia-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clusterpedia-internalstorage
      internalstorage.clusterpedia.io/type: mysql
  template:
    metadata:
      labels:
        app: clusterpedia-internalstorage
        internalstorage.clusterpedia.io/type: mysql
    spec:
      containers:
      - args:
        - --default-authentication-plugin=mysql_native_password
        env:
        - name: MYSQL_DATABASE
          value: clusterpedia
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: internalstorage-password
        image: mysql:8
        name: mysql
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: data
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: internalstorage-mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: clusterpedia-internalstorage
    internalstorage.clusterpedia.io/type: postgres
  name: clusterpedia-internalstorage-postgres
  namespace: clusterpedia-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clusterpedia-internalstorage
      internalstorage.clusterpedia.io/type: postgres
  template:
    metadata:
      labels:
        app: clusterpedia-internalstorage
        internalstorage.clusterpedia.io/type: postgres
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: clusterpedia
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: internalstorage-password
        image: postgres:12
        name: postgres
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: data
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: internalstorage-postgres