apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.pedia.clusterpedia.io
spec:
  insecureSkipTLSVerify: true
  group: pedia.clusterpedia.io
  groupPriorityMinimum: 1000
  versionPriority: 100
  service:
    name: clusterpedia-apiserver
    namespace: clusterpedia-system
  version: v1alpha1
